all:
	latexmk -xelatex main.tex
	make clean
	mv main.pdf hc_final_project_report_team_Hotpot.pdf

clean:
	rm -f *.fdb_latexmk *.fls *.dvi *.aux *.log *.toc *.glo *.idx *.ilg *.out *.bbl *.thm *.blg *.lot *.lof *.xdv